model_list:
  - model_name: gpt-5.4-mini
    litellm_params:
      model: openai/gpt-5.4-mini
      api_base: os.environ/FOUNDRY_API_BASE
      api_key: os.environ/FOUNDRY_API_KEY
    model_info:
      base_model: gpt-5.4-mini
      mode: chat
  - model_name: gpt-5.1
    litellm_params:
      model: openai/gpt-5.1
      api_base: os.environ/FOUNDRY_API_BASE
      api_key: os.environ/FOUNDRY_API_KEY
    model_info:
      base_model: gpt-5.1
      mode: chat

environment_variables:
  UI_USERNAME: admin
  UI_PASSWORD: Mapal@2024

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL